# @file
# @brief Translate REVISION to PROJECT_ID
# @internal
#
# @copyright (C) 2018 Melexis N.V.
#
# Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
#
# THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
# INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
# BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
#
# @endinternal
#
# @ingroup config
#
# @details This file assigns the dependence between chip's revision and the project id's
#

ifeq ($(ORDER_CODE), 81330-xLW-AMx-101)
  PROJECT_ID = 0x050B
  PROJECT_PATH_EXT = A01
  ROM_BASED_LOADER = PPM
  FW_LIN_TL_EMPTY_ERROR_HANDLER = 1
  FW_LIN_TL_LDT_TICK_FIX = 1
  FW_LIN_TL_FUNCTIONAL_NAD_FIX = 1
  CHIP_PACKAGE = QFN24
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
endif

ifeq ($(ORDER_CODE), 81330-xLW-AMx-151)
  PROJECT_ID = 0x050A
  PROJECT_PATH_EXT = A01
  ROM_BASED_LOADER = PPM
  FW_LIN_TL_EMPTY_ERROR_HANDLER = 1
  FW_LIN_TL_LDT_TICK_FIX = 1
  FW_LIN_TL_FUNCTIONAL_NAD_FIX = 1
  CHIP_PACKAGE = QFN24
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
endif

ifeq ($(ORDER_CODE), 81330-xLW-BMx-101)
  PROJECT_ID = 0x0510
  PROJECT_PATH_EXT = B01
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = QFN24
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
  HAS_LIN_AA_DRV_SUP_ENABLE = 1
endif

ifeq ($(ORDER_CODE), 81330-xLW-BMx-102)
  PROJECT_ID = 0x0515
  PROJECT_PATH_EXT = B02
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = QFN24
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
endif

ifeq ($(ORDER_CODE), 81330-xDC-AMx-001)
  PROJECT_ID = 0x0503
  PROJECT_PATH_EXT = A01
  ROM_BASED_LOADER = PPM
  FW_LIN_TL_EMPTY_ERROR_HANDLER = 1
  FW_LIN_TL_LDT_TICK_FIX = 1
  FW_LIN_TL_FUNCTIONAL_NAD_FIX = 1
  CHIP_PACKAGE = SO8
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
endif

ifeq ($(ORDER_CODE), 81330-xDC-AMx-051)
  PROJECT_ID = 0x0502
  PROJECT_PATH_EXT = A01
  ROM_BASED_LOADER = PPM
  FW_LIN_TL_EMPTY_ERROR_HANDLER = 1
  FW_LIN_TL_LDT_TICK_FIX = 1
  FW_LIN_TL_FUNCTIONAL_NAD_FIX = 1
  CHIP_PACKAGE = SO8
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-001)
  PROJECT_ID = 0x050F
  PROJECT_PATH_EXT = B01
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
  HAS_LIN_AA_DRV_SUP_ENABLE = 1
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-101)
  PROJECT_ID = 0x0511
  PROJECT_PATH_EXT = B01
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
  HAS_LIN_AA_DRV_SUP_ENABLE = 1
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-201)
  PROJECT_ID = 0x0512
  PROJECT_PATH_EXT = B01
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-301)
  PROJECT_ID = 0x0513
  PROJECT_PATH_EXT = B01
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-002)
  PROJECT_ID = 0x0514
  PROJECT_PATH_EXT = B02
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-102)
  PROJECT_ID = 0x0516
  PROJECT_PATH_EXT = B02
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
  # lin auto addressing support
  HAS_LIN_AA_CAPABILITY = 1
  HAS_LIN_AA_VDDA_5V = 1
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-202)
  PROJECT_ID = 0x0517
  PROJECT_PATH_EXT = B02
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-302)
  PROJECT_ID = 0x0518
  PROJECT_PATH_EXT = B02
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
endif

ifeq ($(ORDER_CODE), 81330-xDC-BMx-402)
  PROJECT_ID = 0x0519
  PROJECT_PATH_EXT = B02
  ROM_BASED_LOADER = PPM
  CHIP_PACKAGE = SO8
endif

ifndef PROJECT_ID
  $(error 'Error: Unknown order code selected ($(ORDER_CODE)).')
endif


CHIP_REVISION = $(PROJECT_PATH_EXT)

# expose the chip package type to the sources
PLTF_DEFS += CHIP_PACKAGE=$(CHIP_PACKAGE)

# use the current source instead of the pullup in preselection stage from EEPROM calibration version X
LIN_AA_PULLUP_BY_CS_VERSION = 3
