/**
 * @file
 * @brief IO port mapping file
 * @internal
 *
 * @copyright (C) 2020 Melexis N.V.
 * git flash edb9c687
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @details
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81332_RC_2_0_7_20190321_100654
 * Automatic generation by MlxCCT 1.24
 * Template version 1.0.0
 */

#ifndef IO_MAP_H
#define IO_MAP_H

#include <stdint.h>

typedef struct io_rst_ctrl_s {
    uint16_t AWD_WBOOT : 1;
    uint16_t SOFT_WBOOT : 1;
    uint16_t HVDIG_WBOOT : 1;
    uint16_t DBG_WBOOT : 1;
    uint16_t IWD_WBOOT : 1;
    uint16_t reserved_5 : 8;
    uint16_t SOFT_RESET : 1;
    uint16_t HVDIG_USED : 1;
    const uint16_t HVDIG_OK : 1;
} io_rst_ctrl_t;

extern volatile io_rst_ctrl_t RST_CTRL __attribute__((io, addr(0x2)));

typedef struct io_func_test_s {
    uint16_t DISABLE_RESET : 1;
    uint16_t DISABLE_SUSPEND : 1;
    uint16_t DISABLE_IRQ : 1;
    uint16_t reserved_3 : 5;
    uint16_t FTC_SEL : 2;
    uint16_t FTC_DIV : 4;
    uint16_t reserved_14 : 2;
    uint16_t TEST_UNPROT;
} io_func_test_t;

extern volatile io_func_test_t FUNC_TEST __attribute__((io, addr(0x6)));

typedef struct io_mupet_s {
    union {
        uint16_t PTC_SEND;
        const uint16_t PTC_RECEIVE;
    };
    const uint16_t PTCA_PEND : 1;
    const uint16_t PTCS_PEND : 1;
    const uint16_t PTCR_PEND : 1;
    uint16_t reserved_19 : 4;
    const uint16_t PTC_KEY : 1;
    uint16_t WARM_TRIGGER : 5;
    const uint16_t CONNECTION : 2;
    uint16_t IN_APPLICATION : 1;
} io_mupet_t;

extern volatile io_mupet_t MUPET __attribute__((io, addr(0xa)));

typedef struct io_awd_s {
    uint16_t reserved_0 : 6;
    uint16_t ACK : 1;
    uint16_t reserved_7 : 8;
    const uint16_t WIN_OPEN : 1;
} io_awd_t;

extern volatile io_awd_t AWD __attribute__((io, bit_access, addr(0xe)));

typedef struct io_rom_shell_s {
    uint16_t READY : 5;
    uint16_t reserved_5 : 11;
    uint16_t DISABLE_MEM : 1;
} io_rom_shell_t;

extern volatile io_rom_shell_t ROM_SHELL __attribute__((io, addr(0x10)));

typedef struct io_rom_bist_s {
    uint16_t ADD_START_L;
    uint16_t ADD_START_H : 4;
    uint16_t reserved_20 : 12;
    uint16_t ADD_STOP_L;
    uint16_t ADD_STOP_H : 4;
    uint16_t reserved_52 : 12;
    uint16_t SIG_EXPECTED_L;
    uint16_t SIG_EXPECTED_H : 8;
    uint16_t reserved_88 : 8;
    uint16_t ECC_POSITION : 2;
    uint16_t reserved_98 : 2;
    uint16_t BIST : 1;
    uint16_t SINGLE_RAMP : 1;
    uint16_t MASK_SIG_ERR : 1;
    uint16_t reserved_103 : 2;
    const uint16_t BIST_REQUEST : 1;
    uint16_t reserved_106 : 1;
    const uint16_t VALID_CLOCK : 1;
    uint16_t reserved_108 : 3;
    const uint16_t COMPLETED : 1;
    uint16_t START_BIST;
    uint16_t SIG_RECEIVED_L;
    uint16_t SIG_RECEIVED_H : 8;
} io_rom_bist_t;

extern volatile io_rom_bist_t ROM_BIST __attribute__((io, addr(0x14)));

typedef struct io_ram_shell_s {
    uint16_t DISABLE_MEM : 1;
} io_ram_shell_t;

extern volatile io_ram_shell_t RAM_SHELL __attribute__((io, addr(0x2a)));

typedef struct io_iwd_s {
    uint16_t WDT : 8;
    uint16_t DIV : 3;
    uint16_t reserved_11 : 5;
    uint16_t WTG : 8;
    uint16_t reserved_24 : 4;
    uint16_t WIN_ENABLE : 1;
    uint16_t WIN_DISABLE : 1;
    const uint16_t ATT_INT : 1;
    const uint16_t WIN_OPEN : 1;
} io_iwd_t;

extern volatile io_iwd_t IWD __attribute__((io, addr(0x2c)));

typedef struct io_stimer_s {
    const uint16_t CURRENT : 14;
    uint16_t reserved_14 : 2;
    uint16_t VALUE : 14;
    uint16_t MODE : 2;
} io_stimer_t;

extern volatile io_stimer_t STIMER __attribute__((io, addr(0x30)));

typedef struct io_port_adc_ctrl_s {
    uint16_t ADC_INV_COMPOUT : 1;
    uint16_t ADC_EN : 1;
} io_port_adc_ctrl_t;

extern volatile io_port_adc_ctrl_t PORT_ADC_CTRL __attribute__((io, addr(0x34)));

typedef struct io_port_test_adc_s {
    uint16_t TEST_DAC : 1;
    uint16_t TEST_DAC_BUF : 1;
    uint16_t TEST_LDAC : 1;
    uint16_t TEST_HDAC : 1;
    uint16_t TEST_ADC_CURSRC : 1;
    uint16_t TEST_ADC_REF : 2;
    uint16_t TEST_ADC_IN : 2;
} io_port_test_adc_t;

extern volatile io_port_test_adc_t PORT_TEST_ADC __attribute__((io, addr(0x36)));

typedef struct io_mlx16_s {
    uint16_t DBG_DATA0;
    uint16_t DBG_DATA1;
    uint16_t DBG_DATA2;
    uint16_t DBG_DATA3;
    uint16_t DBG_ADDRESS0;
    union {
        uint16_t DBG_CONTROL0;
        struct {
            uint16_t DBG_ADREXT0 : 4;
            uint16_t DBG_COND0 : 4;
            uint16_t DBG_RANGE0 : 1;
            uint16_t DBG_MODE0 : 2;
            const uint16_t DBG_LOCK0 : 1;
            uint16_t DBG_MARKEXT0 : 1;
            uint16_t reserved_93 : 1;
            uint16_t DBG_OVR0 : 1;
            uint16_t DBG_READY0 : 1;
        };
    };
    uint16_t DBG_ADDRESS1;
    union {
        uint16_t DBG_CONTROL1;
        struct {
            uint16_t DBG_ADREXT1 : 4;
            uint16_t DBG_COND1 : 4;
            uint16_t DBG_RANGE1 : 1;
            uint16_t DBG_MODE1 : 2;
            const uint16_t DBG_LOCK1 : 1;
            uint16_t DBG_MARKEXT1 : 1;
            uint16_t reserved_125 : 1;
            uint16_t DBG_OVR1 : 1;
            uint16_t DBG_READY1 : 1;
        };
    };
    uint16_t DBG_ADDRESS2;
    union {
        uint16_t DBG_CONTROL2;
        struct {
            uint16_t DBG_ADREXT2 : 4;
            uint16_t DBG_COND2 : 4;
            uint16_t DBG_RANGE2 : 1;
            uint16_t DBG_MODE2 : 2;
            const uint16_t DBG_LOCK2 : 1;
            uint16_t DBG_MARKEXT2 : 1;
            uint16_t reserved_157 : 1;
            uint16_t DBG_OVR2 : 1;
            uint16_t DBG_READY2 : 1;
        };
    };
    uint16_t DBG_ADDRESS3;
    union {
        uint16_t DBG_CONTROL3;
        struct {
            uint16_t DBG_ADREXT3 : 4;
            uint16_t DBG_COND3 : 4;
            uint16_t DBG_RANGE3 : 1;
            uint16_t DBG_MODE3 : 2;
            const uint16_t DBG_LOCK3 : 1;
            uint16_t DBG_MARKEXT3 : 1;
            uint16_t reserved_189 : 1;
            uint16_t DBG_OVR3 : 1;
            uint16_t DBG_READY3 : 1;
        };
    };
    union {
        uint16_t ITC_PEND0;
        struct {
            uint16_t MLX16_EXCHG_PEND : 1;
            uint16_t MLX16_DMAERR_PEND : 1;
            uint16_t AWD_ATT_PEND : 1;
            uint16_t IWD_ATT_PEND : 1;
            uint16_t FL_ECC_PEND : 1;
            uint16_t EE_ECC_PEND : 1;
            uint16_t UV_VDDA_PEND : 1;
            uint16_t UV_VS_PEND : 1;
            uint16_t UV_VDDAF_PEND : 1;
            uint16_t ANA_PLL_ERR_PEND : 1;
            uint16_t OVT_PEND : 1;
            uint16_t OVC_PEND : 1;
            uint16_t OV_HS_VDS0_PEND : 1;
            uint16_t OV_HS_VDS1_PEND : 1;
            uint16_t OV_HS_VDS2_PEND : 1;
            uint16_t OV_HS_VDS3_PEND : 1;
        };
    };
    union {
        uint16_t ITC_PEND1;
        struct {
            uint16_t OV_LS_VDS0_PEND : 1;
            uint16_t OV_LS_VDS1_PEND : 1;
            uint16_t OV_LS_VDS2_PEND : 1;
            uint16_t OV_LS_VDS3_PEND : 1;
            uint16_t STIMER_PEND : 1;
            uint16_t CTIMER0_1_PEND : 1;
            uint16_t CTIMER0_2_PEND : 1;
            uint16_t CTIMER0_3_PEND : 1;
            uint16_t CTIMER1_1_PEND : 1;
            uint16_t CTIMER1_2_PEND : 1;
            uint16_t CTIMER1_3_PEND : 1;
            uint16_t SPI_TE_PEND : 1;
            uint16_t SPI_RF_PEND : 1;
            uint16_t SPI_ER_PEND : 1;
            uint16_t PWM_MASTER1_CMP_PEND : 1;
            uint16_t PWM_MASTER1_END_PEND : 1;
        };
    };
    union {
        uint16_t ITC_PEND2;
        struct {
            uint16_t PWM_SLAVE1_CMP_PEND : 1;
            uint16_t PWM_SLAVE2_CMP_PEND : 1;
            uint16_t PWM_SLAVE3_CMP_PEND : 1;
            uint16_t PWM_MASTER2_CMP_PEND : 1;
            uint16_t PWM_MASTER2_END_PEND : 1;
            uint16_t ADC_SAR_PEND : 1;
            uint16_t EE_COMPLETE_PEND : 1;
            uint16_t FL_COMPLETE_PEND : 1;
            uint16_t COLIN_OWNMTX_PEND : 1;
            uint16_t COLIN_LIN_PEND : 1;
            uint16_t OV_VS_PEND : 1;
            uint16_t DIAG_PEND : 1;
            uint16_t I2C_GLOBAL_RESET_PEND : 1;
            uint16_t PPM_RX_PEND : 1;
            uint16_t PPM_TX_PEND : 1;
            uint16_t PPM_ERR_PEND : 1;
        };
    };
    union {
        uint16_t ITC_PEND3;
        struct {
            uint16_t IO_IN0_PEND : 1;
            uint16_t IO_IN1_PEND : 1;
            uint16_t IO_IN2_PEND : 1;
            uint16_t IO_IN3_PEND : 1;
            uint16_t IO_IN4_PEND : 1;
            uint16_t IO_IN5_PEND : 1;
            uint16_t IO_IN6_PEND : 1;
            uint16_t IO_IN7_PEND : 1;
            uint16_t UART_SB_PEND : 1;
            uint16_t UART_RS_PEND : 1;
            uint16_t UART_RR_PEND : 1;
            uint16_t UART_TS_PEND : 1;
            uint16_t UART_TR_PEND : 1;
            uint16_t UART_TE_PEND : 1;
            uint16_t UDFR_PEND : 1;
            uint16_t UDTF_PEND : 1;
        };
    };
    union {
        uint16_t ITC_PEND4 : 2;
        struct {
            uint16_t TX_TIMEOUT_PEND : 1;
            uint16_t MLX16_SOFT_PEND : 1;
            uint16_t reserved_258 : 14;
        };
    };
    uint16_t reserved_272;
    uint16_t reserved_288;
    uint16_t reserved_304;
    uint16_t reserved_320;
    uint16_t reserved_336;
    uint16_t reserved_352;
    uint16_t reserved_368;
    uint16_t reserved_384;
    uint16_t reserved_400 : 15;
    uint16_t SWI : 1;
    union {
        uint16_t ITC_MASK0;
        struct {
            uint16_t MLX16_EXCHG_ITC : 1;
            uint16_t MLX16_DMAERR_ITC : 1;
            uint16_t AWD_ATT_ITC : 1;
            uint16_t IWD_ATT_ITC : 1;
            uint16_t FL_ECC_ITC : 1;
            uint16_t EE_ECC_ITC : 1;
            uint16_t UV_VDDA_ITC : 1;
            uint16_t UV_VS_ITC : 1;
            uint16_t UV_VDDAF_ITC : 1;
            uint16_t ANA_PLL_ERR_ITC : 1;
            uint16_t OVT_ITC : 1;
            uint16_t OVC_ITC : 1;
            uint16_t OV_HS_VDS0_ITC : 1;
            uint16_t OV_HS_VDS1_ITC : 1;
            uint16_t OV_HS_VDS2_ITC : 1;
            uint16_t OV_HS_VDS3_ITC : 1;
        };
    };
    union {
        uint16_t ITC_MASK1;
        struct {
            uint16_t OV_LS_VDS0_ITC : 1;
            uint16_t OV_LS_VDS1_ITC : 1;
            uint16_t OV_LS_VDS2_ITC : 1;
            uint16_t OV_LS_VDS3_ITC : 1;
            uint16_t STIMER_ITC : 1;
            uint16_t CTIMER0_1_ITC : 1;
            uint16_t CTIMER0_2_ITC : 1;
            uint16_t CTIMER0_3_ITC : 1;
            uint16_t CTIMER1_1_ITC : 1;
            uint16_t CTIMER1_2_ITC : 1;
            uint16_t CTIMER1_3_ITC : 1;
            uint16_t SPI_TE_ITC : 1;
            uint16_t SPI_RF_ITC : 1;
            uint16_t SPI_ER_ITC : 1;
            uint16_t PWM_MASTER1_CMP_ITC : 1;
            uint16_t PWM_MASTER1_END_ITC : 1;
        };
    };
    union {
        uint16_t ITC_MASK2;
        struct {
            uint16_t PWM_SLAVE1_CMP_ITC : 1;
            uint16_t PWM_SLAVE2_CMP_ITC : 1;
            uint16_t PWM_SLAVE3_CMP_ITC : 1;
            uint16_t PWM_MASTER2_CMP_ITC : 1;
            uint16_t PWM_MASTER2_END_ITC : 1;
            uint16_t ADC_SAR_ITC : 1;
            uint16_t EE_COMPLETE_ITC : 1;
            uint16_t FL_COMPLETE_ITC : 1;
            uint16_t COLIN_OWNMTX_ITC : 1;
            uint16_t COLIN_LIN_ITC : 1;
            uint16_t OV_VS_ITC : 1;
            uint16_t DIAG_ITC : 1;
            uint16_t I2C_GLOBAL_RESET_ITC : 1;
            uint16_t PPM_RX_ITC : 1;
            uint16_t PPM_TX_ITC : 1;
            uint16_t PPM_ERR_ITC : 1;
        };
    };
    union {
        uint16_t ITC_MASK3;
        struct {
            uint16_t IO_IN0_ITC : 1;
            uint16_t IO_IN1_ITC : 1;
            uint16_t IO_IN2_ITC : 1;
            uint16_t IO_IN3_ITC : 1;
            uint16_t IO_IN4_ITC : 1;
            uint16_t IO_IN5_ITC : 1;
            uint16_t IO_IN6_ITC : 1;
            uint16_t IO_IN7_ITC : 1;
            uint16_t UART_SB_ITC : 1;
            uint16_t UART_RS_ITC : 1;
            uint16_t UART_RR_ITC : 1;
            uint16_t UART_TS_ITC : 1;
            uint16_t UART_TR_ITC : 1;
            uint16_t UART_TE_ITC : 1;
            uint16_t UDFR_ITC : 1;
            uint16_t UDTF_ITC : 1;
        };
    };
    union {
        uint16_t ITC_MASK4 : 2;
        struct {
            uint16_t TX_TIMEOUT_ITC : 1;
            uint16_t MLX16_SOFT_ITC : 1;
            uint16_t reserved_482 : 14;
        };
    };
    uint16_t reserved_496;
    uint16_t reserved_512;
    uint16_t reserved_528;
    uint16_t reserved_544;
    uint16_t reserved_560;
    uint16_t reserved_576;
    uint16_t reserved_592;
    uint16_t reserved_608;
    uint16_t reserved_624;
    union {
        uint16_t ITC_PRIO0;
        struct {
            uint16_t STIMER_PRIO : 2;
            uint16_t CTIMER0_1_PRIO : 2;
            uint16_t CTIMER0_2_PRIO : 2;
            uint16_t CTIMER0_3_PRIO : 2;
            uint16_t CTIMER1_1_PRIO : 2;
            uint16_t CTIMER1_2_PRIO : 2;
            uint16_t CTIMER1_3_PRIO : 2;
            uint16_t SPI_TE_PRIO : 2;
        };
    };
    union {
        uint16_t ITC_PRIO1;
        struct {
            uint16_t SPI_RF_PRIO : 2;
            uint16_t SPI_ER_PRIO : 2;
            uint16_t PWM_MASTER1_CMP_PRIO : 2;
            uint16_t PWM_MASTER1_END_PRIO : 2;
            uint16_t PWM_SLAVE1_CMP_PRIO : 2;
            uint16_t PWM_SLAVE2_CMP_PRIO : 2;
            uint16_t PWM_SLAVE3_CMP_PRIO : 2;
            uint16_t PWM_MASTER2_CMP_PRIO : 2;
        };
    };
    union {
        uint16_t ITC_PRIO2;
        struct {
            uint16_t PWM_MASTER2_END_PRIO : 2;
            uint16_t ADC_SAR_PRIO : 2;
            uint16_t EE_COMPLETE_PRIO : 2;
            uint16_t FL_COMPLETE_PRIO : 2;
            uint16_t COLIN_OWNMTX_PRIO : 2;
            uint16_t COLIN_LIN_PRIO : 2;
            uint16_t OV_VS_PRIO : 2;
            uint16_t DIAG_PRIO : 2;
        };
    };
    union {
        uint16_t ITC_PRIO3;
        struct {
            uint16_t I2C_GLOBAL_RESET_PRIO : 2;
            uint16_t PPM_RX_PRIO : 2;
            uint16_t PPM_TX_PRIO : 2;
            uint16_t PPM_ERR_PRIO : 2;
            uint16_t IO_IN0_PRIO : 2;
            uint16_t IO_IN1_PRIO : 2;
            uint16_t IO_IN2_PRIO : 2;
            uint16_t IO_IN3_PRIO : 2;
        };
    };
    union {
        uint16_t ITC_PRIO4;
        struct {
            uint16_t IO_IN4_PRIO : 2;
            uint16_t IO_IN5_PRIO : 2;
            uint16_t IO_IN6_PRIO : 2;
            uint16_t IO_IN7_PRIO : 2;
            uint16_t UART_SB_PRIO : 2;
            uint16_t UART_RS_PRIO : 2;
            uint16_t UART_RR_PRIO : 2;
            uint16_t UART_TS_PRIO : 2;
        };
    };
    union {
        uint16_t ITC_PRIO5 : 10;
        struct {
            uint16_t UART_TR_PRIO : 2;
            uint16_t UART_TE_PRIO : 2;
            uint16_t UDFR_PRIO : 2;
            uint16_t UDTF_PRIO : 2;
            uint16_t TX_TIMEOUT_PRIO : 2;
            uint16_t reserved_730 : 6;
        };
    };
    uint16_t reserved_736;
    uint16_t reserved_752;
    uint16_t reserved_768;
    uint16_t reserved_784;
    uint16_t reserved_800;
    uint16_t reserved_816;
    uint16_t reserved_832;
    uint16_t reserved_848;
    uint16_t reserved_864;
    uint16_t reserved_880;
    uint16_t reserved_896;
    uint16_t reserved_912;
    uint16_t reserved_928;
    uint16_t reserved_944;
    uint16_t reserved_960;
    uint16_t reserved_976;
    uint16_t reserved_992;
    uint16_t reserved_1008;
    uint16_t reserved_1024;
    uint16_t reserved_1040;
    uint16_t reserved_1056;
    const uint16_t SHELL_VERSION;
    uint16_t CPU_FP0ADR : 12;
} io_mlx16_t;

extern volatile io_mlx16_t MLX16 __attribute__((nodp, addr(0x38)));

typedef struct io_version_s {
    const uint16_t VERSION_L;
    const uint16_t VERSION_H;
} io_version_t;

extern volatile io_version_t VERSION __attribute__((nodp, addr(0x100)));

typedef struct io_ram_bist_s {
    union {
        uint16_t KEY;
        struct {
            const uint16_t PHASE : 3;
            uint16_t reserved_3 : 5;
            const uint16_t TRANSPARENT : 1;
            const uint16_t REGULAR : 1;
            const uint16_t RUNNING : 1;
            const uint16_t VALID_CLOCK : 1;
            const uint16_t REGULAR_BIST_ERROR : 1;
            uint16_t reserved_13 : 2;
            const uint16_t COMPLETED : 1;
        };
    };
    union {
        const uint16_t LFSR;
        const uint16_t LSFR_GOT;
    };
    const uint16_t LFSR_EXPECTED;
    const uint16_t ADL;
    const uint16_t ADH : 4;
    uint16_t reserved_68 : 12;
    uint16_t ADD_START_L;
    uint16_t ADD_START_H : 4;
    uint16_t reserved_100 : 12;
    uint16_t ADD_STOP_L;
    uint16_t ADD_STOP_H : 4;
    uint16_t reserved_132 : 12;
    uint16_t NB_ECC_BITS : 5;
    uint16_t WORD_BIST : 1;
    uint16_t FUNCTIONAL_BIST : 1;
    uint16_t reserved_151 : 1;
    uint16_t ADD_SCRAMBLE : 3;
    uint16_t reserved_155 : 1;
    uint16_t SIGNATURE_INIT : 1;
} io_ram_bist_t;

extern volatile io_ram_bist_t RAM_BIST __attribute__((nodp, addr(0x104)));

typedef struct io_ctimer0_s {
    uint16_t TREGB;
    uint16_t TREGA;
    const uint16_t TCNT;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t EDGA : 2;
    uint16_t EDGB : 2;
    const uint16_t PWMI : 1;
    uint16_t POL : 1;
    const uint16_t OVRA : 1;
    const uint16_t OVRB : 1;
    uint16_t ENCMP : 1;
    uint16_t MODE : 3;
    uint16_t DIV : 2;
} io_ctimer0_t;

extern volatile io_ctimer0_t CTIMER0 __attribute__((nodp, addr(0x118)));

typedef struct io_ctimer1_s {
    uint16_t TREGB;
    uint16_t TREGA;
    const uint16_t TCNT;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t EDGA : 2;
    uint16_t EDGB : 2;
    const uint16_t PWMI : 1;
    uint16_t POL : 1;
    const uint16_t OVRA : 1;
    const uint16_t OVRB : 1;
    uint16_t ENCMP : 1;
    uint16_t MODE : 3;
    uint16_t DIV : 2;
} io_ctimer1_t;

extern volatile io_ctimer1_t CTIMER1 __attribute__((nodp, addr(0x120)));

typedef struct io_spi_s {
    uint16_t DR;
    uint16_t SBASE;
    uint16_t RBASE;
    uint16_t MSGLEN : 6;
    uint16_t reserved_54 : 10;
    uint16_t PSCLN : 4;
    uint16_t PSCLM : 4;
    uint16_t reserved_72 : 8;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t MASTER : 1;
    uint16_t SS_FORCE : 1;
    uint16_t BYTE_MODE : 1;
    uint16_t CPOL : 1;
    uint16_t CPHA : 1;
    uint16_t DMA : 1;
    uint16_t TX_EN : 1;
    uint16_t RX_EN : 1;
    uint16_t reserved_90 : 2;
    const uint16_t TE : 1;
    const uint16_t RF : 1;
    uint16_t OVRF : 1;
    uint16_t MODF : 1;
} io_spi_t;

extern volatile io_spi_t SPI __attribute__((nodp, addr(0x128)));

typedef struct io_pwm_master1_s {
    uint16_t CMP;
    uint16_t HT;
    uint16_t LT;
    uint16_t PER;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t SLAVE : 1;
    uint16_t MODE : 2;
    uint16_t POL : 1;
    uint16_t IDLE : 1;
    const uint16_t PWM_IN : 1;
    uint16_t PSCLN : 4;
    uint16_t PSCLM : 4;
} io_pwm_master1_t;

extern volatile io_pwm_master1_t PWM_MASTER1 __attribute__((nodp, addr(0x134)));

typedef struct io_pwm_slave1_s {
    uint16_t CMP;
    uint16_t HT;
    uint16_t LT;
    const uint16_t PER;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t SLAVE : 1;
    uint16_t MODE : 2;
    uint16_t POL : 1;
    uint16_t IDLE : 1;
    const uint16_t PWM_IN : 1;
    uint16_t PSCLN : 4;
    uint16_t PSCLM : 4;
} io_pwm_slave1_t;

extern volatile io_pwm_slave1_t PWM_SLAVE1 __attribute__((nodp, addr(0x13e)));

typedef struct io_pwm_slave2_s {
    uint16_t CMP;
    uint16_t HT;
    uint16_t LT;
    const uint16_t PER;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t SLAVE : 1;
    uint16_t MODE : 2;
    uint16_t POL : 1;
    uint16_t IDLE : 1;
    const uint16_t PWM_IN : 1;
    uint16_t PSCLN : 4;
    uint16_t PSCLM : 4;
} io_pwm_slave2_t;

extern volatile io_pwm_slave2_t PWM_SLAVE2 __attribute__((nodp, addr(0x148)));

typedef struct io_pwm_slave3_s {
    uint16_t CMP;
    uint16_t HT;
    uint16_t LT;
    const uint16_t PER;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t SLAVE : 1;
    uint16_t MODE : 2;
    uint16_t POL : 1;
    uint16_t IDLE : 1;
    const uint16_t PWM_IN : 1;
    uint16_t PSCLN : 4;
    uint16_t PSCLM : 4;
} io_pwm_slave3_t;

extern volatile io_pwm_slave3_t PWM_SLAVE3 __attribute__((nodp, addr(0x152)));

typedef struct io_pwm_master2_s {
    uint16_t CMP;
    uint16_t HT;
    uint16_t LT;
    uint16_t PER;
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t SLAVE : 1;
    uint16_t MODE : 2;
    uint16_t POL : 1;
    uint16_t IDLE : 1;
    const uint16_t PWM_IN : 1;
    uint16_t PSCLN : 4;
    uint16_t PSCLM : 4;
} io_pwm_master2_t;

extern volatile io_pwm_master2_t PWM_MASTER2 __attribute__((nodp, addr(0x15c)));

typedef struct io_adc_sar_s {
    uint16_t START : 1;
    uint16_t STOP : 1;
    uint16_t SOS_SOURCE : 2;
    uint16_t SOC_SOURCE : 2;
    uint16_t NO_INTERLEAVE : 1;
    uint16_t SATURATE : 1;
    uint16_t INT_SCHEME : 2;
    uint16_t ASB : 2;
    uint16_t ADC_WIDTH : 1;
    uint16_t reserved_13 : 3;
    uint16_t SBASE_0;
    uint16_t PAUSE : 1;
    uint16_t RESUME : 1;
    uint16_t SW_TRIG : 1;
    uint16_t READY : 1;
    uint16_t LAST_INT_SRC : 2;
    uint16_t STATE : 2;
    uint16_t ADC_OVF : 1;
    uint16_t ADC_ERR : 1;
    uint16_t MEM_ERR : 1;
    uint16_t FRAME_ERR : 1;
    uint16_t ABORTED : 1;
    uint16_t reserved_45 : 3;
    uint16_t ADC_CLK_DIV : 7;
    uint16_t reserved_55 : 9;
    uint16_t TEST_CONV2 : 1;
    uint16_t TEST_CONV3 : 1;
    uint16_t TEST_CONV4 : 1;
    uint16_t TEST_TRIM : 1;
    uint16_t reserved_68 : 12;
    uint16_t ADC_DATA : 10;
    uint16_t SEL_TR_ADCREF : 1;
    uint16_t reserved_91 : 5;
    uint16_t TR_ADCREF1 : 7;
    uint16_t TR_ADCREF2 : 7;
    uint16_t reserved_110 : 2;
    uint16_t TR_ADCREF3 : 7;
    uint16_t IDDQ_ADC : 1;
} io_adc_sar_t;

extern volatile io_adc_sar_t ADC_SAR __attribute__((nodp, addr(0x166)));

typedef struct io_eeprom_flash_s {
    uint16_t T_10NS : 1;
    uint16_t reserved_1 : 1;
    uint16_t T_50NS : 3;
    uint16_t T_10US : 5;
    uint16_t T_50US : 5;
    uint16_t LOCK_T : 1;
    uint16_t T_1US : 5;
    uint16_t reserved_21 : 10;
    uint16_t LOCK_1US : 1;
    uint16_t FL_DMA : 1;
    uint16_t FL_BUFFER_MODE : 1;
    uint16_t reserved_34 : 2;
    const uint16_t EE_FL_VERSION : 4;
    uint16_t EE_DMA : 1;
    uint16_t EE_EXTEND_DATA : 1;
    uint16_t EE_BUFFER_MODE : 1;
    uint16_t reserved_43 : 4;
    uint16_t EE_FL_PDN_LOW : 1;
    union {
        uint16_t FL_COMMAND;
        struct {
            const uint16_t FL_STATUS : 4;
            uint16_t reserved_52 : 12;
        };
    };
    uint16_t FL_ER_TIME : 8;
    uint16_t FL_WR_TIME : 7;
    uint16_t FL_LOCK_ER_WR : 1;
    uint16_t FL_WAIT_STATES : 3;
    uint16_t reserved_83 : 1;
    uint16_t FL_BYPASS_QUEUE : 1;
    uint16_t reserved_85 : 1;
    uint16_t FL_PREDICTION_BEHAVIOR : 2;
    uint16_t FL_DED_RETRY : 3;
    uint16_t reserved_91 : 1;
    uint16_t FL_HALT_BEHAVIOR : 2;
    uint16_t reserved_94 : 1;
    uint16_t FL_LOCK_RDY : 1;
    uint16_t FL_SBE : 1;
    uint16_t FL_DATA_CORRUPTED : 1;
    uint16_t reserved_98 : 6;
    uint16_t FL_EXTENDED_DATA : 1;
    uint16_t reserved_105 : 7;
    uint16_t FL_PAGE_NUMBER : 4;
    uint16_t FL_SECTOR_NUMBER : 4;
    uint16_t FL_CS_AREA : 1;
    uint16_t reserved_121 : 3;
    uint16_t FL_32K_SELEC : 2;
    uint16_t reserved_126 : 2;
    uint16_t EE_ACTIVE : 1;
    uint16_t EE_CONFIGURED : 1;
    uint16_t reserved_130 : 2;
    uint16_t EE_WE_KEY : 4;
    uint16_t EE_W_MODE : 3;
    uint16_t reserved_139 : 1;
    const uint16_t EE_BUSY_BUF_NOT_EMPTY : 1;
    const uint16_t EE_BUSY_WR : 1;
    const uint16_t EE_BUSY_STBY : 1;
    const uint16_t EE_BUSY : 1;
    uint16_t EE_SBE_1 : 1;
    uint16_t EE_DATA_CORRUPTED_1 : 1;
    uint16_t EE_SBE_2 : 1;
    uint16_t EE_DATA_CORRUPTED_2 : 1;
    uint16_t reserved_148 : 12;
    uint16_t EE_PRE_WR_TIME : 7;
    uint16_t reserved_167 : 1;
    uint16_t EE_WR_TIME : 7;
    uint16_t EE_LOCK_WR : 1;
    uint16_t EE_ER_TIME : 6;
    uint16_t reserved_182 : 9;
    uint16_t EE_LOCK_ER : 1;
    uint16_t EE_PROGRAM_CYCLE : 5;
    uint16_t reserved_197 : 10;
    uint16_t EE_PROGRAM_CYCLE_LOCK : 1;
    uint16_t EE_HALT_BEHAVIOR : 2;
    uint16_t reserved_210 : 6;
    uint16_t EE_WAIT_STATES : 4;
    uint16_t reserved_220 : 3;
    uint16_t EE_LOCK_RD : 1;
    uint16_t EE_INT_INVALID_SRC : 4;
    uint16_t reserved_228 : 12;
    uint16_t reserved_240;
    uint16_t reserved_256;
    uint16_t reserved_272;
    uint16_t reserved_288;
    uint16_t reserved_304 : 4;
    uint16_t FL_PATTERN_ID : 3;
    uint16_t reserved_311 : 1;
    uint16_t FL_ACCESS_ORDER : 2;
    uint16_t FL_TEST_AREA : 2;
    uint16_t reserved_316 : 2;
    const uint16_t FL_ERROR : 1;
    uint16_t FL_COMPLETED : 1;
    uint16_t FL_BITS_ERRORS : 9;
    uint16_t reserved_329 : 7;
    uint16_t FL_SIG_L;
    uint16_t FL_SIG_H;
    uint16_t EE_CMD : 2;
    uint16_t reserved_370 : 2;
    uint16_t EE_PATTERN_ID : 3;
    uint16_t reserved_375 : 1;
    uint16_t EE_ACCESS_ORDER : 2;
    uint16_t EE_TEST_AREA : 2;
    uint16_t reserved_380 : 1;
    const uint16_t EE_IN_PROGRESS : 1;
    const uint16_t EE_ERROR : 1;
    uint16_t EE_COMPLETED : 1;
    uint16_t EE_BITS_ERRORS : 9;
    uint16_t reserved_393 : 7;
    uint16_t EE_SIG_L;
    uint16_t EE_SIG_H;
} io_eeprom_flash_t;

extern volatile io_eeprom_flash_t EEPROM_FLASH __attribute__((nodp, addr(0x176)));

typedef struct io_colin_s {
    uint16_t ADDR_PATCH0 : 12;
    uint16_t CTRL_PATCH0 : 1;
    uint16_t reserved_13 : 3;
    uint16_t DATA_PATCH0;
    uint16_t ADDR_PATCH1 : 12;
    uint16_t CTRL_PATCH1 : 1;
    uint16_t reserved_45 : 3;
    uint16_t DATA_PATCH1;
    uint16_t ADDR_PATCH2 : 12;
    uint16_t CTRL_PATCH2 : 1;
    uint16_t reserved_77 : 3;
    uint16_t DATA_PATCH2;
    uint16_t ADDR_PATCH3 : 12;
    uint16_t CTRL_PATCH3 : 1;
    uint16_t reserved_109 : 3;
    uint16_t DATA_PATCH3;
    uint16_t SPEED : 3;
    uint16_t RUN : 1;
    uint16_t reserved_132 : 4;
    uint16_t SIGNAL : 1;
    uint16_t ERROR : 1;
    uint16_t HANDSHAKE : 1;
    uint16_t EVENT : 1;
    uint16_t reserved_140 : 4;
    uint16_t COMMAND : 8;
    uint16_t SLAVE_IT : 8;
    uint16_t RAM_ACCESS : 3;
    uint16_t reserved_163 : 1;
    uint16_t RAM_SETUP : 1;
    uint16_t reserved_165 : 3;
    uint16_t ROM_ACCESS : 3;
    uint16_t reserved_171 : 1;
    uint16_t ROM_SETUP : 1;
    uint16_t reserved_173 : 3;
    uint16_t DISABLE_ROM : 1;
    uint16_t reserved_177 : 7;
    uint16_t DISABLE_RAM : 1;
    uint16_t reserved_185 : 7;
    uint16_t RAM_PROT_LIMIT : 8;
    uint16_t reserved_200 : 7;
    uint16_t LOCK : 1;
} io_colin_t;

extern volatile io_colin_t COLIN __attribute__((nodp, addr(0x1ac)));

typedef struct io_port_lin_xkey_s {
    uint16_t LIN_XKEY;
} io_port_lin_xkey_t;

extern volatile io_port_lin_xkey_t PORT_LIN_XKEY __attribute__((nodp, addr(0x1c6)));

typedef struct io_trim_bg_bias_s {
    uint16_t PRE_TR_BGA : 4;
    uint16_t PRE_TR_BGD : 4;
    uint16_t PRE_TR_BIAS : 6;
    uint16_t TR_UNUSED : 1;
    uint16_t LOCK : 1;
} io_trim_bg_bias_t;

extern volatile io_trim_bg_bias_t TRIM_BG_BIAS __attribute__((nodp, addr(0x1c8)));

typedef struct io_trim_vdd_s {
    uint16_t PRE_TR_VDDA : 3;
    uint16_t PRE_TR_VDDD : 3;
    uint16_t PRE_TR_SUP : 8;
    uint16_t TR_UNUSED : 1;
    uint16_t LOCK : 1;
} io_trim_vdd_t;

extern volatile io_trim_vdd_t TRIM_VDD __attribute__((nodp, addr(0x1ca)));

typedef struct io_trim_rco32m_s {
    uint16_t TR_RCO32M_IN : 10;
    uint16_t TR_UNUSED : 5;
    uint16_t LOCK : 1;
} io_trim_rco32m_t;

extern volatile io_trim_rco32m_t TRIM_RCO32M __attribute__((nodp, addr(0x1cc)));

typedef struct io_trim_rco1m_s {
    uint16_t PRE_TR_RCO1M : 8;
    uint16_t PRE_TR_LIN_SLEWRATE : 3;
    uint16_t PRE_TR_LIN_SLVTERM : 3;
    uint16_t TR_UNUSED : 1;
    uint16_t LOCK : 1;
} io_trim_rco1m_t;

extern volatile io_trim_rco1m_t TRIM_RCO1M __attribute__((nodp, addr(0x1ce)));

typedef struct io_port_sscm_conf_s {
    uint16_t SSCM_EN : 1;
    uint16_t SSCM_SINGLEBIT : 1;
    uint16_t SSCM_CENTERED : 1;
} io_port_sscm_conf_t;

extern volatile io_port_sscm_conf_t PORT_SSCM_CONF __attribute__((nodp, addr(0x1d0)));

typedef struct io_port_step_conf_s {
    uint16_t STEP_INC : 4;
    uint16_t STEP_DUR : 4;
    uint16_t STEP_CNT : 8;
} io_port_step_conf_t;

extern volatile io_port_step_conf_t PORT_STEP_CONF __attribute__((nodp, addr(0x1d2)));

typedef struct io_port_supp_test_s {
    uint16_t TEST_BGA : 1;
    uint16_t TEST_VAUX_ADDCURRENT : 1;
    uint16_t TEST_10U_BIAS : 1;
    uint16_t TEST_5U_BIASAUX : 1;
    uint16_t PORTEST : 1;
    uint16_t SWITCHOFFREG_VDDA : 2;
    uint16_t SWITCHOFFREG_VDDD : 2;
    uint16_t SWITCHOFFUV_VDDD_RES : 1;
    uint16_t SBY_BIAS : 1;
    uint16_t LOW_VDDD : 1;
    uint16_t SHOVE_VDDD : 1;
    uint16_t SHOVE_VDDA : 1;
    uint16_t SHOVE_VAUX : 1;
} io_port_supp_test_t;

extern volatile io_port_supp_test_t PORT_SUPP_TEST __attribute__((nodp, addr(0x1d4)));

typedef struct io_port_supp2_test_s {
    uint16_t IDDQ_REG_VDDA : 1;
    uint16_t IDDQ_REG_VDDD : 1;
    uint16_t IDDQSENS_REG_VDDD : 1;
    uint16_t INT_WU_TEST : 1;
    uint16_t TEST_TA0_EN : 1;
    uint16_t TEST_TA1_EN : 1;
    uint16_t TEST_MEM_ANA : 1;
    uint16_t IDDQ_TEMPSENSE : 1;
    uint16_t IDDQ_CLK10K : 1;
    uint16_t TST_VDDA_OUT2_FV : 1;
    uint16_t TST_VDDD_OUT2_FV : 1;
    uint16_t TST_IO_LV : 1;
    uint16_t FGTSM : 1;
    uint16_t FSTOP : 1;
} io_port_supp2_test_t;

extern volatile io_port_supp2_test_t PORT_SUPP2_TEST __attribute__((nodp, addr(0x1d6)));

typedef struct io_port_lin_test_s {
    uint16_t TEST_2U8_BIASLIN : 1;
} io_port_lin_test_t;

extern volatile io_port_lin_test_t PORT_LIN_TEST __attribute__((nodp, addr(0x1d8)));

typedef struct io_port_spare_test_s {
    uint16_t SET_IOX_CONN2PHV : 1;
    uint16_t RST_IOX_CONN2PHV : 1;
    uint16_t TST_VDDA_VT_MON_SUP : 1;
    uint16_t CPCLKSEL_DRV : 2;
    uint16_t TST_HS_SHORT_DET : 2;
    uint16_t TST_FLASH_LV0_1 : 1;
} io_port_spare_test_t;

extern volatile io_port_spare_test_t PORT_SPARE_TEST __attribute__((nodp, addr(0x1da)));

typedef struct io_port_adc_trim_test_s {
    uint16_t SEL_TR_BGA : 1;
    uint16_t SEL_TR_BGD : 1;
    uint16_t SEL_TR_VDDA : 1;
    uint16_t SEL_TR_VDDD : 1;
    uint16_t SEL_TR_BIAS : 1;
    uint16_t SEL_TR_SUP : 1;
    uint16_t SEL_TR_LIN_SLEWRATE : 1;
    uint16_t SEL_TR_LIN_SLVTERM : 1;
    uint16_t SEL_TR_RCO32M : 1;
    uint16_t SEL_TR_RCO1M : 1;
} io_port_adc_trim_test_t;

extern volatile io_port_adc_trim_test_t PORT_ADC_TRIM_TEST __attribute__((nodp, addr(0x1dc)));

typedef struct io_port_io_in_s {
    const uint16_t IO_IN_SYNC : 8;
} io_port_io_in_t;

extern volatile io_port_io_in_t PORT_IO_IN __attribute__((nodp, addr(0x1de)));

typedef struct io_port_supp_in_s {
    const uint16_t UV_VDDA_IT : 1;
    const uint16_t UV_VDDA_SYNC : 1;
    const uint16_t UV_VS_IT : 1;
    const uint16_t UV_VS_SYNC : 1;
    const uint16_t OV_VS_IT : 1;
    const uint16_t OV_VS_SYNC : 1;
    const uint16_t OVT_IT : 1;
    const uint16_t OVT_SYNC : 1;
    const uint16_t OVC_IT : 1;
    const uint16_t OVC_SYNC : 1;
    const uint16_t UV_VDDAF_IT : 1;
    const uint16_t UV_VDDAF_SYNC : 1;
} io_port_supp_in_t;

extern volatile io_port_supp_in_t PORT_SUPP_IN __attribute__((nodp, addr(0x1e0)));

typedef struct io_port_misc_in_s {
    const uint16_t AIN_SUP : 8;
    const uint16_t STOP_MODE : 1;
    const uint16_t RSTAT : 1;
    const uint16_t INTERNAL_WU : 1;
    const uint16_t LIN_WU : 1;
    const uint16_t PHYSTAT1 : 1;
    const uint16_t LIN_RXD : 1;
    const uint16_t LOCAL_WU : 1;
    const uint16_t XOR_WU_IO : 1;
} io_port_misc_in_t;

extern volatile io_port_misc_in_t PORT_MISC_IN __attribute__((nodp, addr(0x1e2)));

typedef struct io_port_supp_cfg_s {
    uint16_t UV_VDDA_FILT_SEL : 1;
    uint16_t UV_VDDAF_FILT_SEL : 2;
    uint16_t UV_VS_FILT_SEL : 1;
    uint16_t OV_VS_FILT_SEL : 1;
    uint16_t OVC_FILT_SEL : 1;
    uint16_t OVT_FILT_SEL : 1;
} io_port_supp_cfg_t;

extern volatile io_port_supp_cfg_t PORT_SUPP_CFG __attribute__((nodp, addr(0x1e4)));

typedef struct io_port_io_out_soft_s {
    uint16_t IO_OUT_SOFT : 8;
} io_port_io_out_soft_t;

extern volatile io_port_io_out_soft_t PORT_IO_OUT_SOFT __attribute__((nodp, addr(0x1e6)));

typedef struct io_port_io_out_en_s {
    uint16_t reserved_0 : 4;
    uint16_t IO_CH_SEL : 3;
    uint16_t IO0_LV_ENABLE : 1;
    uint16_t IO0_OD_ENABLE : 1;
    uint16_t IOX_OD_ENABLE : 1;
} io_port_io_out_en_t;

extern volatile io_port_io_out_en_t PORT_IO_OUT_EN __attribute__((nodp, addr(0x1e8)));

typedef struct io_port_io_cfg0_s {
    uint16_t IO0_OUT_SEL : 4;
    uint16_t IO1_OUT_SEL : 4;
    uint16_t IO2_OUT_SEL : 4;
    uint16_t IO3_OUT_SEL : 4;
} io_port_io_cfg0_t;

extern volatile io_port_io_cfg0_t PORT_IO_CFG0 __attribute__((nodp, addr(0x1ea)));

typedef struct io_port_lin_xtx_cfg_s {
    uint16_t LIN_XTX_OUT_SEL : 4;
    uint16_t LIN_COLIN_RX_SEL : 2;
    uint16_t LIN_OUT_SOFT : 1;
    uint16_t LIN_IN_SOFT : 1;
} io_port_lin_xtx_cfg_t;

extern volatile io_port_lin_xtx_cfg_t PORT_LIN_XTX_CFG __attribute__((nodp, addr(0x1ec)));

typedef struct io_port_timer_cfg_s {
    uint16_t TIMER0_CHA_SEL : 5;
    uint16_t reserved_5 : 3;
    uint16_t TIMER0_CHB_SEL : 5;
} io_port_timer_cfg_t;

extern volatile io_port_timer_cfg_t PORT_TIMER_CFG __attribute__((nodp, addr(0x1ee)));

typedef struct io_port_comm_cfg_s {
    uint16_t SPI_MOSI_IN_SEL : 3;
    uint16_t reserved_3 : 1;
    uint16_t SPI_MISO_IN_SEL : 3;
    uint16_t reserved_7 : 1;
    uint16_t SPI_SCK_IN_SEL : 3;
    uint16_t reserved_11 : 1;
    uint16_t SPI_SS_IN_SEL : 3;
} io_port_comm_cfg_t;

extern volatile io_port_comm_cfg_t PORT_COMM_CFG __attribute__((nodp, addr(0x1f0)));

typedef struct io_port_misc_out_s {
    uint16_t CLEAR_STOP : 1;
    uint16_t SET_RSTAT : 1;
    uint16_t CLEAR_RSTAT : 1;
    uint16_t WUI : 2;
    uint16_t SWITCH_VDDA_TO_5V : 1;
    uint16_t PRUV_VS : 3;
    uint16_t PROV_VS : 2;
    uint16_t PRUV_VDDA : 1;
    uint16_t SEL_TEMP : 4;
} io_port_misc_out_t;

extern volatile io_port_misc_out_t PORT_MISC_OUT __attribute__((nodp, addr(0x1f2)));

typedef struct io_port_misc2_out_s {
    uint16_t ENABLE_OSD_DRV : 2;
    uint16_t reserved_2 : 2;
    uint16_t AOUT_SUP : 4;
    uint16_t WU_IO_EN : 1;
    uint16_t ENABLE_OTD : 1;
    uint16_t VSM_FILT_ON : 1;
} io_port_misc2_out_t;

extern volatile io_port_misc2_out_t PORT_MISC2_OUT __attribute__((nodp, addr(0x1f4)));

typedef struct io_port_stopmd_ctrl_s {
    uint16_t SEL_STOP_MODE : 1;
} io_port_stopmd_ctrl_t;

extern volatile io_port_stopmd_ctrl_t PORT_STOPMD_CTRL __attribute__((nodp, addr(0x1f6)));

typedef struct io_port_stopmd_cfg_s {
    uint16_t PRE_SWITCHOFFUV_VDDA : 1;
    uint16_t PRE_SWITCHOFFUV_VS : 1;
    uint16_t PRE_SWITCHOFFOV_VS : 1;
    uint16_t PRE_SBY_RCO32M : 1;
    uint16_t PRE_SBY_RCO1M : 1;
} io_port_stopmd_cfg_t;

extern volatile io_port_stopmd_cfg_t PORT_STOPMD_CFG __attribute__((nodp, addr(0x1f8)));

typedef struct io_port_dis_gtsm_s {
    uint16_t DIS_GTSM : 1;
} io_port_dis_gtsm_t;

extern volatile io_port_dis_gtsm_t PORT_DIS_GTSM __attribute__((nodp, addr(0x1fa)));

typedef struct io_port_lin_xcfg_s {
    uint16_t LIN_XCFG;
} io_port_lin_xcfg_t;

extern volatile io_port_lin_xcfg_t PORT_LIN_XCFG __attribute__((nodp, addr(0x1fc)));

typedef struct io_port_lin_xcfg_valid_s {
    const uint16_t LIN_XCFG_VALID;
} io_port_lin_xcfg_valid_t;

extern volatile io_port_lin_xcfg_valid_t PORT_LIN_XCFG_VALID __attribute__((nodp, addr(0x1fe)));

typedef struct io_port_clock_ctrl_s {
    uint16_t AC_SEL : 1;
} io_port_clock_ctrl_t;

extern volatile io_port_clock_ctrl_t PORT_CLOCK_CTRL __attribute__((nodp, addr(0x200)));

typedef struct io_port_linaa1_s {
    uint16_t LINAA_GAIN : 4;
    uint16_t LINAA_DIV : 5;
    uint16_t LINAA_RST1 : 1;
    uint16_t LINAA_RST2 : 1;
    uint16_t LINAA_EN : 1;
    uint16_t LINAA_CDOUTEN : 1;
} io_port_linaa1_t;

extern volatile io_port_linaa1_t PORT_LINAA1 __attribute__((nodp, addr(0x202)));

typedef struct io_port_linaa2_s {
    uint16_t LCD_SEL_LINAA : 3;
    uint16_t LCD_ON_LINAA : 1;
    uint16_t LCD_DIS_LINAA : 1;
} io_port_linaa2_t;

extern volatile io_port_linaa2_t PORT_LINAA2 __attribute__((nodp, addr(0x204)));

typedef struct io_trim_misc_s {
    uint16_t TRIM_LCD_LINAA : 6;
    uint16_t TRIM_OTD : 6;
    uint16_t TRIM_SDAFILT_IO : 2;
    uint16_t reserved_14 : 1;
    uint16_t LOCK : 1;
} io_trim_misc_t;

extern volatile io_trim_misc_t TRIM_MISC __attribute__((nodp, addr(0x206)));

typedef struct io_trim1_drv_s {
    uint16_t TRIM_DRVSUP : 2;
    uint16_t PRE_TRIM_DRVMOD_CPCLK : 10;
    uint16_t reserved_12 : 3;
    uint16_t LOCK : 1;
} io_trim1_drv_t;

extern volatile io_trim1_drv_t TRIM1_DRV __attribute__((nodp, addr(0x208)));

typedef struct io_trim2_drv_s {
    uint16_t TRIM_SLWRT : 4;
    uint16_t TRIM_CSA_GAIN : 5;
    uint16_t TRIM_CP_SLWRT_DRV : 4;
    uint16_t reserved_13 : 2;
    uint16_t LOCK : 1;
} io_trim2_drv_t;

extern volatile io_trim2_drv_t TRIM2_DRV __attribute__((nodp, addr(0x20a)));

typedef struct io_trim3_drv_s {
    uint16_t TRIM_CSA_CL : 8;
    uint16_t reserved_8 : 7;
    uint16_t LOCK : 1;
} io_trim3_drv_t;

extern volatile io_trim3_drv_t TRIM3_DRV __attribute__((nodp, addr(0x20c)));

typedef struct io_port_drv_out_s {
    uint16_t ENABLE_DRVSUP : 1;
    uint16_t ENABLE_DRVMOD_CPCLK : 1;
    uint16_t ENABLE_DRV : 4;
    uint16_t ENABLE_CSA : 1;
    uint16_t ENABLE_HS_OC : 1;
    uint16_t ENABLE_LS_OC : 1;
    uint16_t DRVMOD_OPTION : 2;
    uint16_t PARALLEL_MODE_DRV : 1;
} io_port_drv_out_t;

extern volatile io_port_drv_out_t PORT_DRV_OUT __attribute__((nodp, addr(0x20e)));

typedef struct io_port_drv1_test_s {
    uint16_t TST_HS_OC_ISENSE : 4;
    uint16_t TST_LS_OC_ISENSE : 4;
    uint16_t TST_STRS_VHS_HS_DRV : 1;
    uint16_t TST_STRS_VHS_LS_DRV : 1;
    uint16_t TST_OUT_LV1 : 4;
    uint16_t TST_UVCMP_LV1_DRVSUP : 1;
    uint16_t TST_VBGCS_LV0_DRVSUP : 1;
} io_port_drv1_test_t;

extern volatile io_port_drv1_test_t PORT_DRV1_TEST __attribute__((nodp, addr(0x210)));

typedef struct io_port_drv2_test_s {
    uint16_t TST_OUT_HV0 : 4;
    uint16_t TST_OUT_LV0 : 4;
    uint16_t TST_DRVSUP : 1;
    uint16_t TEST_DRVMOD_CPCLK : 1;
    uint16_t TEST_DRV_ILD : 2;
    uint16_t TST_OC_REDUCE_LVL : 1;
    uint16_t TST_DRVSUP_DISC_CMP : 1;
} io_port_drv2_test_t;

extern volatile io_port_drv2_test_t PORT_DRV2_TEST __attribute__((nodp, addr(0x212)));

typedef struct io_port_drv3_test_s {
    uint16_t TST_GHS_NOCURR : 4;
    uint16_t TST_HS_GHS_IBOOST_HRDOFFSW : 1;
    uint16_t TST_CSA_RS : 1;
    uint16_t TST_CSA_FR : 1;
    uint16_t TST_CSA_OC : 1;
    uint16_t TST_AMP_DIV_LV0_CSA : 1;
    uint16_t TST_DAC_LV0_CSA : 1;
    uint16_t TST_V5V_DIV3 : 1;
    uint16_t TST_DRVMOD_CPCLK_DAC : 1;
} io_port_drv3_test_t;

extern volatile io_port_drv3_test_t PORT_DRV3_TEST __attribute__((nodp, addr(0x214)));

typedef struct io_port_drv_ctrl_s {
    uint16_t DRV0_CTRL : 4;
    uint16_t DRV1_CTRL : 4;
    uint16_t DRV2_CTRL : 4;
    uint16_t DRV3_CTRL : 4;
} io_port_drv_ctrl_t;

extern volatile io_port_drv_ctrl_t PORT_DRV_CTRL __attribute__((nodp, addr(0x216)));

typedef struct io_port_drv1_prot_s {
    uint16_t OVT_PM : 1;
    uint16_t DIS_OVT : 1;
    uint16_t OV_VS_PM : 1;
    uint16_t DIS_OV_VS : 1;
    uint16_t UV_VS_PM : 1;
    uint16_t DIS_UV_VS : 1;
    uint16_t UV_VDDA_PM : 1;
    uint16_t DIS_UV_VDDA : 1;
    uint16_t UV_VDDAF_PM : 1;
    uint16_t DIS_UV_VDDAF : 1;
    uint16_t OC_PM : 1;
    uint16_t DIS_OC : 1;
    uint16_t OV_HS_VDS_PM : 1;
    uint16_t DIS_OV_HS_VDS : 1;
    uint16_t OV_LS_VDS_PM : 1;
    uint16_t DIS_OV_LS_VDS : 1;
} io_port_drv1_prot_t;

extern volatile io_port_drv1_prot_t PORT_DRV1_PROT __attribute__((nodp, addr(0x218)));

typedef struct io_port_drv2_prot_s {
    uint16_t DIS_DRV : 1;
} io_port_drv2_prot_t;

extern volatile io_port_drv2_prot_t PORT_DRV2_PROT __attribute__((nodp, addr(0x21a)));

typedef struct io_port_drv_in_s {
    const uint16_t OV_HS_VDS_SYNC : 4;
    const uint16_t OV_HS_VDS0_IT : 1;
    const uint16_t OV_HS_VDS1_IT : 1;
    const uint16_t OV_HS_VDS2_IT : 1;
    const uint16_t OV_HS_VDS3_IT : 1;
    const uint16_t OV_LS_VDS_SYNC : 4;
    const uint16_t OV_LS_VDS0_IT : 1;
    const uint16_t OV_LS_VDS1_IT : 1;
    const uint16_t OV_LS_VDS2_IT : 1;
    const uint16_t OV_LS_VDS3_IT : 1;
} io_port_drv_in_t;

extern volatile io_port_drv_in_t PORT_DRV_IN __attribute__((nodp, addr(0x21c)));

typedef struct io_port_diag_in_s {
    const uint16_t OVT_MEM : 1;
    const uint16_t OV_VS_MEM : 1;
    const uint16_t UV_VS_MEM : 1;
    const uint16_t UV_VDDA_MEM : 1;
    const uint16_t UV_VDDAF_MEM : 1;
    const uint16_t OVC_MEM : 1;
    const uint16_t OV_HS_VDS_MEM : 4;
    const uint16_t OV_LS_VDS_MEM : 4;
} io_port_diag_in_t;

extern volatile io_port_diag_in_t PORT_DIAG_IN __attribute__((nodp, addr(0x21e)));

typedef struct io_port_i2c_conf_s {
    uint16_t I2C_ADDR : 7;
    uint16_t I2C_ADDR_VALID : 1;
    uint16_t SDA_FILT_ENABLE : 1;
    uint16_t I2C_SCL_CLK_SEL : 3;
} io_port_i2c_conf_t;

extern volatile io_port_i2c_conf_t PORT_I2C_CONF __attribute__((nodp, addr(0x220)));

typedef struct io_port_i2c_dma_offset_s {
    uint16_t I2C_DMA_OFFSET;
} io_port_i2c_dma_offset_t;

extern volatile io_port_i2c_dma_offset_t PORT_I2C_DMA_OFFSET __attribute__((nodp, addr(0x222)));

typedef struct io_port_i2c_read_offset_s {
    uint16_t I2C_READ_OFFSET : 8;
} io_port_i2c_read_offset_t;

extern volatile io_port_i2c_read_offset_t PORT_I2C_READ_OFFSET __attribute__((nodp, addr(0x224)));

typedef struct io_port_misc_test_s {
    uint16_t TST_CMP_LV0_OTD : 1;
    uint16_t TST_DISC_DIO_OTD : 1;
    uint16_t TST_RESREF_LV0_OTD : 1;
    uint16_t TST_LV0_BUF_ENABLE : 1;
    uint16_t TST_LV0_IO0 : 1;
    uint16_t TST_LV1_IO0 : 1;
    uint16_t LINAA_TST_VREF : 2;
    uint16_t DIS_TX_TIMEOUT : 1;
} io_port_misc_test_t;

extern volatile io_port_misc_test_t PORT_MISC_TEST __attribute__((nodp, addr(0x226)));

typedef struct io_port_ppm_rbase_add_s {
    uint16_t PPM_RBASE_ADD;
} io_port_ppm_rbase_add_t;

extern volatile io_port_ppm_rbase_add_t PORT_PPM_RBASE_ADD __attribute__((nodp, addr(0x228)));

typedef struct io_port_ppm_tbase_add_s {
    uint16_t PPM_TBASE_ADD;
} io_port_ppm_tbase_add_t;

extern volatile io_port_ppm_tbase_add_t PORT_PPM_TBASE_ADD __attribute__((nodp, addr(0x22a)));

typedef struct io_port_ppm_timeout_s {
    uint16_t PPM_TIMEOUT;
} io_port_ppm_timeout_t;

extern volatile io_port_ppm_timeout_t PORT_PPM_TIMEOUT __attribute__((nodp, addr(0x22c)));

typedef struct io_port_ppm_ctrl_s {
    uint16_t PPM_EN : 1;
    uint16_t PPM_RE_FE : 1;
    uint16_t PPM_DMA_LEN : 4;
    uint16_t PPM_FILT_BYP : 1;
    uint16_t PPM_MODE : 1;
    uint16_t PPM_DAT_IT_NB : 2;
    uint16_t PPM_TX_RX : 1;
    uint16_t PPM_IN_SEL : 4;
} io_port_ppm_ctrl_t;

extern volatile io_port_ppm_ctrl_t PORT_PPM_CTRL __attribute__((nodp, addr(0x22e)));

typedef struct io_port_ppm_buf_data_s {
    const uint16_t PPM_BUF_DATA;
} io_port_ppm_buf_data_t;

extern volatile io_port_ppm_buf_data_t PORT_PPM_BUF_DATA __attribute__((nodp, addr(0x230)));

typedef struct io_ppm_timer_s {
    uint16_t PPM_ON_TIME;
} io_ppm_timer_t;

extern volatile io_ppm_timer_t PPM_TIMER __attribute__((nodp, addr(0x232)));

typedef struct io_port_ppm_flags_s {
    const uint16_t PPM_DMA_OP : 1;
    const uint16_t PPM_RCVF : 1;
    const uint16_t PPM_TOUT : 1;
    const uint16_t PPM_DMA_ERR : 1;
} io_port_ppm_flags_t;

extern volatile io_port_ppm_flags_t PORT_PPM_FLAGS __attribute__((nodp, addr(0x234)));

typedef struct io_port_sscm2_conf_s {
    uint16_t SSCM2_EN : 1;
    uint16_t SSCM2_SINGLEBIT : 1;
    uint16_t SSCM2_CENTERED : 1;
} io_port_sscm2_conf_t;

extern volatile io_port_sscm2_conf_t PORT_SSCM2_CONF __attribute__((nodp, addr(0x236)));

typedef struct io_port_step2_conf_s {
    uint16_t STEP2_INC : 4;
    uint16_t STEP2_DUR : 4;
    uint16_t STEP2_CNT : 8;
} io_port_step2_conf_t;

extern volatile io_port_step2_conf_t PORT_STEP2_CONF __attribute__((nodp, addr(0x238)));

typedef struct io_port_io_enable_s {
    uint16_t IO_ENABLE : 8;
    uint16_t IO_DISREC : 8;
} io_port_io_enable_t;

extern volatile io_port_io_enable_t PORT_IO_ENABLE __attribute__((nodp, addr(0x23a)));

typedef struct io_port_io_cfg1_s {
    uint16_t IO4_OUT_SEL : 4;
    uint16_t IO5_OUT_SEL : 4;
    uint16_t IO6_OUT_SEL : 4;
    uint16_t IO7_OUT_SEL : 4;
} io_port_io_cfg1_t;

extern volatile io_port_io_cfg1_t PORT_IO_CFG1 __attribute__((nodp, addr(0x23c)));

typedef struct io_port_timer_cfg1_s {
    uint16_t TIMER1_CHA_SEL : 5;
    uint16_t reserved_5 : 3;
    uint16_t TIMER1_CHB_SEL : 5;
} io_port_timer_cfg1_t;

extern volatile io_port_timer_cfg1_t PORT_TIMER_CFG1 __attribute__((nodp, addr(0x23e)));

typedef struct io_port_io_trig_edge_cfg_s {
    uint16_t IO0_TRIG_EDGE_SEL : 2;
    uint16_t IO1_TRIG_EDGE_SEL : 2;
    uint16_t IO2_TRIG_EDGE_SEL : 2;
    uint16_t IO3_TRIG_EDGE_SEL : 2;
    uint16_t IO4_TRIG_EDGE_SEL : 2;
    uint16_t IO5_TRIG_EDGE_SEL : 2;
    uint16_t IO6_TRIG_EDGE_SEL : 2;
    uint16_t IO7_TRIG_EDGE_SEL : 2;
} io_port_io_trig_edge_cfg_t;

extern volatile io_port_io_trig_edge_cfg_t PORT_IO_TRIG_EDGE_CFG __attribute__((nodp, addr(0x240)));

typedef struct io_port_comm_cfg1_s {
    uint16_t UART_RX_SEL : 3;
} io_port_comm_cfg1_t;

extern volatile io_port_comm_cfg1_t PORT_COMM_CFG1 __attribute__((nodp, addr(0x242)));

typedef struct io_port_udma_rda_s {
    uint16_t UDMA_RDA;
} io_port_udma_rda_t;

extern volatile io_port_udma_rda_t PORT_UDMA_RDA __attribute__((nodp, addr(0x244)));

typedef struct io_port_udma_rdb_s {
    uint16_t UDMA_RDB;
} io_port_udma_rdb_t;

extern volatile io_port_udma_rdb_t PORT_UDMA_RDB __attribute__((nodp, addr(0x246)));

typedef struct io_port_udma_tx_s {
    uint16_t UDMA_TX;
} io_port_udma_tx_t;

extern volatile io_port_udma_tx_t PORT_UDMA_TX __attribute__((nodp, addr(0x248)));

typedef struct io_port_udma_size_s {
    uint16_t UDMA_SIZRX : 8;
    uint16_t UDMA_SIZTX : 8;
} io_port_udma_size_t;

extern volatile io_port_udma_size_t PORT_UDMA_SIZE __attribute__((nodp, addr(0x24a)));

typedef struct io_port_udma_ctrl_s {
    uint16_t UDMA_EN : 1;
    uint16_t UDMA_TXSTART : 1;
    uint16_t UDMA_LSB_FIRST : 1;
    uint16_t UDMA_LOWBYTE_FIRST : 1;
    uint16_t UART_STOP_MODE : 1;
} io_port_udma_ctrl_t;

extern volatile io_port_udma_ctrl_t PORT_UDMA_CTRL __attribute__((nodp, addr(0x24c)));

typedef struct io_uart_s {
    uint16_t BRRD;
    uint16_t TRD;
    const uint16_t RRD;
    const uint16_t LFCD : 8;
    uint16_t LFDD : 8;
    uint16_t reserved_64 : 1;
    uint16_t TRE : 1;
    uint16_t REE : 1;
    uint16_t ISB : 1;
    uint16_t reserved_68 : 1;
    const uint16_t LBE : 1;
    const uint16_t LSE : 1;
    const uint16_t LTE : 1;
    uint16_t MLS : 3;
    uint16_t BSC : 2;
    uint16_t LBC : 1;
    uint16_t LSC : 1;
    uint16_t LDC : 1;
    uint16_t reserved_80 : 8;
    const uint16_t TRO : 1;
    const uint16_t TRB : 1;
    const uint16_t TSB : 1;
    const uint16_t RSO : 1;
    const uint16_t RSB : 1;
    const uint16_t RRF : 1;
    const uint16_t NBR : 1;
    const uint16_t SBE : 1;
} io_uart_t;

extern volatile io_uart_t UART __attribute__((nodp, addr(0x24e)));

typedef struct io_port_udma_status_s {
    const uint16_t UDMA_RD_BUFFER_VALID : 1;
    const uint16_t UDMA_FRC : 1;
    const uint16_t UDMA_FTR : 1;
    const uint16_t CUSTOM_UART_DMA_ERR : 1;
} io_port_udma_status_t;

extern volatile io_port_udma_status_t PORT_UDMA_STATUS __attribute__((nodp, addr(0x25a)));

typedef struct io_port_tx_timeout_s {
    const uint16_t TX_TIMEOUT : 1;
} io_port_tx_timeout_t;

extern volatile io_port_tx_timeout_t PORT_TX_TIMEOUT __attribute__((nodp, addr(0x25c)));

#endif /* IO_MAP_H */

/* EOF */
