/**
 * @file
 * @brief Weak implementations of the interrupt handlers.
 * @internal
 *
 * @copyright (C) 2019 Melexis N.V.
 * git flash edb9c687
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @ingroup fw_user_startup
 *
 * @details This file contains the implementations of weak interrupt handlers.
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81332_RC_2_0_7_20190321_100654
 */

#include "syslib.h"
#include "error_handler.h"


/* ---------------------------------------------
 * Function Definitions
 * --------------------------------------------- */

/* Default interrupt handler for MLX16_EXCHG.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _MLX16_EXCHG_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for MLX16_DMAERR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _MLX16_DMAERR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for AWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _AWD_ATT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IWD_ATT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for FL_ECC.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _FL_ECC_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for EE_ECC.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _EE_ECC_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UV_VDDA.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UV_VDDA_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UV_VS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UV_VS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UV_VDDAF.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UV_VDDAF_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for ANA_PLL_ERR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _ANA_PLL_ERR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OVT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OVT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OVC.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OVC_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_HS_VDS0.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_HS_VDS0_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_HS_VDS1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_HS_VDS1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_HS_VDS2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_HS_VDS2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_HS_VDS3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_HS_VDS3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_LS_VDS0.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_LS_VDS0_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_LS_VDS1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_LS_VDS1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_LS_VDS2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_LS_VDS2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_LS_VDS3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_LS_VDS3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for STIMER.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _STIMER_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER0_1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER0_1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER0_2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER0_2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER0_3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER0_3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER1_1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER1_1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER1_2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER1_2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER1_3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER1_3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for SPI_TE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _SPI_TE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for SPI_RF.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _SPI_RF_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for SPI_ER.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _SPI_ER_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER1_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER1_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER1_END.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER1_END_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_SLAVE1_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_SLAVE1_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_SLAVE2_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_SLAVE2_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_SLAVE3_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_SLAVE3_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER2_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER2_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER2_END.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER2_END_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for ADC_SAR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _ADC_SAR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for EE_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _EE_COMPLETE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for FL_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _FL_COMPLETE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for COLIN_OWNMTX.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _COLIN_OWNMTX_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for COLIN_LIN.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _COLIN_LIN_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_VS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_VS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for DIAG.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _DIAG_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for I2C_GLOBAL_RESET.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _I2C_GLOBAL_RESET_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PPM_RX.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PPM_RX_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PPM_TX.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PPM_TX_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PPM_ERR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PPM_ERR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN0.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN0_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN4.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN4_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN5.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN5_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN6.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN6_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN7.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN7_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART_SB.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART_SB_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART_RS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART_RS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART_RR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART_RR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART_TS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART_TS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART_TR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART_TR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART_TE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART_TE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UDFR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UDFR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UDTF.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UDTF_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for TX_TIMEOUT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _TX_TIMEOUT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for MLX16_SOFT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _MLX16_SOFT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

