/**
 * @file
 * @brief Weak implementations of the interrupt handlers.
 * @internal
 *
 * @copyright (C) 2022 Melexis N.V.
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @ingroup fw_user_startup
 *
 * @details This file contains the implementations of weak interrupt handlers.
 * This file is based on autogenerated file for 81334.
 */

/*
 * This is a temporary implementation until the camcu_platform that contains the updated
 * version of "unused interrupt vector handlers" becomes available.
 * When the updated camcu_platform becomes available this file must be deleted (together with its .h)
 * In the new camcu_platform the function ErrH_NonInlineFatalInformed will become available, causing
 * the linker to complain about double symbol definition.
 */

#include "syslib.h"
#include "error_handler.h"
#include "memory_map.h"
#include "memory_map_vectors.h"

/* ---------------------------------------------
 * Function Definitions
 * --------------------------------------------- */

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !! ErrH_NonInlineFatalInformed is copied from future camcu_platform.
 * !! It is not even used by this program, its only purpose is to make the linker generate
 * !! an warning->error about a duplicate definition of this symbol.
 * !! when the linker throws this error this complete file and its .h must be removed
 * !! from the application src directory
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */
void NOINLINE ErrH_NonInlineFatalInformed(ErrH_Identifier information)
{
    ErrH_FatalInformed(information);
}

#ifndef HAS_SW_EXPLICIT_FAIL_INFO
/* Generic interrupt handler */
WEAK_INTERRUPT void Generic_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for MLX16_EXCHG.
 * The handler can be overwritten by application sources. */
WEAK void _MLX16_EXCHG_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for MLX16_DMAERR.
 * The handler can be overwritten by application sources. */
WEAK void _MLX16_DMAERR_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for AWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK void _AWD_ATT_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK void _IWD_ATT_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for FL_ECC.
 * The handler can be overwritten by application sources. */
WEAK void _FL_ECC_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for EE_ECC.
 * The handler can be overwritten by application sources. */
WEAK void _EE_ECC_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UV_VDDA.
 * The handler can be overwritten by application sources. */
WEAK void _UV_VDDA_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UV_VS.
 * The handler can be overwritten by application sources. */
WEAK void _UV_VS_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UV_VDDAF.
 * The handler can be overwritten by application sources. */
WEAK void _UV_VDDAF_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for ANA_PLL_ERR.
 * The handler can be overwritten by application sources. */
WEAK void _ANA_PLL_ERR_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OVT.
 * The handler can be overwritten by application sources. */
WEAK void _OVT_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OVC.
 * The handler can be overwritten by application sources. */
WEAK void _OVC_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_HS_VDS0.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS0_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_HS_VDS1.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS1_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_HS_VDS2.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS2_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_HS_VDS3.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS3_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_LS_VDS0.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS0_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_LS_VDS1.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS1_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_LS_VDS2.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS2_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_LS_VDS3.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS3_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for STIMER.
 * The handler can be overwritten by application sources. */
WEAK void _STIMER_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for CTIMER0_1.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER0_1_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for CTIMER0_2.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER0_2_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for CTIMER0_3.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER0_3_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for CTIMER1_1.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER1_1_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for CTIMER1_2.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER1_2_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for CTIMER1_3.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER1_3_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for SPI_TE.
 * The handler can be overwritten by application sources. */
WEAK void _SPI_TE_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for SPI_RF.
 * The handler can be overwritten by application sources. */
WEAK void _SPI_RF_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for SPI_ER.
 * The handler can be overwritten by application sources. */
WEAK void _SPI_ER_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PWM_MASTER1_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER1_CMP_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PWM_MASTER1_END.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER1_END_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PWM_SLAVE1_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_SLAVE1_CMP_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PWM_SLAVE2_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_SLAVE2_CMP_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PWM_SLAVE3_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_SLAVE3_CMP_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PWM_MASTER2_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER2_CMP_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PWM_MASTER2_END.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER2_END_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for ADC_SAR.
 * The handler can be overwritten by application sources. */
WEAK void _ADC_SAR_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for EE_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK void _EE_COMPLETE_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for FL_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK void _FL_COMPLETE_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for COLIN_OWNMTX.
 * The handler can be overwritten by application sources. */
WEAK void _COLIN_OWNMTX_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for COLIN_LIN.
 * The handler can be overwritten by application sources. */
WEAK void _COLIN_LIN_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for OV_VS.
 * The handler can be overwritten by application sources. */
WEAK void _OV_VS_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for DIAG.
 * The handler can be overwritten by application sources. */
WEAK void _DIAG_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for I2C_GLOBAL_RESET.
 * The handler can be overwritten by application sources. */
WEAK void _I2C_GLOBAL_RESET_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PPM_RX.
 * The handler can be overwritten by application sources. */
WEAK void _PPM_RX_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PPM_TX.
 * The handler can be overwritten by application sources. */
WEAK void _PPM_TX_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for PPM_ERR.
 * The handler can be overwritten by application sources. */
WEAK void _PPM_ERR_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IO_IN0.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN0_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IO_IN1.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN1_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IO_IN2.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN2_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IO_IN3.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN3_INT(void) __attribute__((alias("Generic_INT")));

#if defined(MLX81332) || defined(MLX81334)
/* Default interrupt handler for IO_IN4.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN4_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IO_IN5.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN5_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IO_IN6.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN6_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for IO_IN7.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN7_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UART_SB.
 * The handler can be overwritten by application sources. */
WEAK void _UART_SB_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UART_RS.
 * The handler can be overwritten by application sources. */
WEAK void _UART_RS_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UART_RR.
 * The handler can be overwritten by application sources. */
WEAK void _UART_RR_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UART_TS.
 * The handler can be overwritten by application sources. */
WEAK void _UART_TS_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UART_TR.
 * The handler can be overwritten by application sources. */
WEAK void _UART_TR_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UART_TE.
 * The handler can be overwritten by application sources. */
WEAK void _UART_TE_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UDFR.
 * The handler can be overwritten by application sources. */
WEAK void _UDFR_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for UDTF.
 * The handler can be overwritten by application sources. */
WEAK void _UDTF_INT(void) __attribute__((alias("Generic_INT")));
#endif /* defined (MLX81332) || defined (MLX81334) */

/* Default interrupt handler for TX_TIMEOUT.
 * The handler can be overwritten by application sources. */
WEAK void _TX_TIMEOUT_INT(void) __attribute__((alias("Generic_INT")));

#if defined(MLX81334)
/* Default interrupt handler for I2C_EOW.
 * The handler can be overwritten by application sources. */
WEAK void _I2C_EOW_INT(void) __attribute__((alias("Generic_INT")));

/* Default interrupt handler for I2C_EOR.
 * The handler can be overwritten by application sources. */
WEAK void _I2C_EOR_INT(void) __attribute__((alias("Generic_INT")));
#endif /* defined (MLX81334) */

/* Default interrupt handler for MLX16_SOFT.
 * The handler can be overwritten by application sources. */
WEAK void _MLX16_SOFT_INT(void) __attribute__((alias("Generic_INT")));

#else /* HAS_SW_EXPLICIT_FAIL_INFO */

/*
 * ErrH_NonInlineVectorFatalInformed is copied from future camcu_platform
 * It is not declared static because when the future camcu_platform becomes available
 * it will cause a linker error, warning the user that this complete file must be removed
 */

/** Sets the BistError to desired error handler identifier and stores the interrupt information in BistErrorInfo
 *
 * @param[in] id holds the reason of failure to indicate
 * @param[in] interrupt_offset  Interrupt offset of the active interrupt vector table
 */
INLINE void ErrH_SetVectorInfo(ErrH_Identifier id, uint16_t interrupt_offset)
{
    bistError = id;
    bistErrorInfo = interrupt_offset;
}

INLINE void ErrH_VectorFatalInformed(uint16_t interrupt_offset)
{
    ErrH_SetVectorInfo(FAIL_UNHANDLED_ISR, interrupt_offset);
    _fatal();
}

void NOINLINE ErrH_NonInlineVectorFatalInformed(uint16_t interrupt_offset)
{
    ErrH_VectorFatalInformed(interrupt_offset);
}

/* Default interrupt handler for MLX16_EXCHG.
 * The handler can be overwritten by application sources. */
WEAK void _MLX16_EXCHG_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_MLX16_EXCHG);
}

/* Default interrupt handler for MLX16_DMAERR.
 * The handler can be overwritten by application sources. */
WEAK void _MLX16_DMAERR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_MLX16_DMAERR);
}

/* Default interrupt handler for AWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK void _AWD_ATT_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_AWD_ATT);
}

/* Default interrupt handler for IWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK void _IWD_ATT_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IWD_ATT);
}

/* Default interrupt handler for FL_ECC.
 * The handler can be overwritten by application sources. */
WEAK void _FL_ECC_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_FL_ECC);
}

/* Default interrupt handler for EE_ECC.
 * The handler can be overwritten by application sources. */
WEAK void _EE_ECC_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_EE_ECC);
}

/* Default interrupt handler for UV_VDDA.
 * The handler can be overwritten by application sources. */
WEAK void _UV_VDDA_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UV_VDDA);
}

/* Default interrupt handler for UV_VS.
 * The handler can be overwritten by application sources. */
WEAK void _UV_VS_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UV_VS);
}

/* Default interrupt handler for UV_VDDAF.
 * The handler can be overwritten by application sources. */
WEAK void _UV_VDDAF_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UV_VDDAF);
}

/* Default interrupt handler for ANA_PLL_ERR.
 * The handler can be overwritten by application sources. */
WEAK void _ANA_PLL_ERR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_ANA_PLL_ERR);
}

/* Default interrupt handler for OVT.
 * The handler can be overwritten by application sources. */
WEAK void _OVT_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OVT);
}

/* Default interrupt handler for OVC.
 * The handler can be overwritten by application sources. */
WEAK void _OVC_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OVC);
}

/* Default interrupt handler for OV_HS_VDS0.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS0_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_HS_VDS0);
}

/* Default interrupt handler for OV_HS_VDS1.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS1_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_HS_VDS1);
}

/* Default interrupt handler for OV_HS_VDS2.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS2_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_HS_VDS2);
}

/* Default interrupt handler for OV_HS_VDS3.
 * The handler can be overwritten by application sources. */
WEAK void _OV_HS_VDS3_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_HS_VDS3);
}

/* Default interrupt handler for OV_LS_VDS0.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS0_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_LS_VDS0);
}

/* Default interrupt handler for OV_LS_VDS1.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS1_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_LS_VDS1);
}

/* Default interrupt handler for OV_LS_VDS2.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS2_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_LS_VDS2);
}

/* Default interrupt handler for OV_LS_VDS3.
 * The handler can be overwritten by application sources. */
WEAK void _OV_LS_VDS3_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_LS_VDS3);
}

/* Default interrupt handler for STIMER.
 * The handler can be overwritten by application sources. */
WEAK void _STIMER_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_STIMER);
}

/* Default interrupt handler for CTIMER0_1.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER0_1_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_CTIMER0_1);
}

/* Default interrupt handler for CTIMER0_2.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER0_2_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_CTIMER0_2);
}

/* Default interrupt handler for CTIMER0_3.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER0_3_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_CTIMER0_3);
}

/* Default interrupt handler for CTIMER1_1.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER1_1_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_CTIMER1_1);
}

/* Default interrupt handler for CTIMER1_2.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER1_2_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_CTIMER1_2);
}

/* Default interrupt handler for CTIMER1_3.
 * The handler can be overwritten by application sources. */
WEAK void _CTIMER1_3_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_CTIMER1_3);
}

/* Default interrupt handler for SPI_TE.
 * The handler can be overwritten by application sources. */
WEAK void _SPI_TE_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_SPI_TE);
}

/* Default interrupt handler for SPI_RF.
 * The handler can be overwritten by application sources. */
WEAK void _SPI_RF_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_SPI_RF);
}

/* Default interrupt handler for SPI_ER.
 * The handler can be overwritten by application sources. */
WEAK void _SPI_ER_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_SPI_ER);
}

/* Default interrupt handler for PWM_MASTER1_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER1_CMP_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PWM_MASTER1_CMP);
}

/* Default interrupt handler for PWM_MASTER1_END.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER1_END_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PWM_MASTER1_END);
}

/* Default interrupt handler for PWM_SLAVE1_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_SLAVE1_CMP_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PWM_SLAVE1_CMP);
}

/* Default interrupt handler for PWM_SLAVE2_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_SLAVE2_CMP_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PWM_SLAVE2_CMP);
}

/* Default interrupt handler for PWM_SLAVE3_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_SLAVE3_CMP_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PWM_SLAVE3_CMP);
}

/* Default interrupt handler for PWM_MASTER2_CMP.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER2_CMP_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PWM_MASTER2_CMP);
}

/* Default interrupt handler for PWM_MASTER2_END.
 * The handler can be overwritten by application sources. */
WEAK void _PWM_MASTER2_END_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PWM_MASTER2_END);
}

/* Default interrupt handler for ADC_SAR.
 * The handler can be overwritten by application sources. */
WEAK void _ADC_SAR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_ADC_SAR);
}

/* Default interrupt handler for EE_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK void _EE_COMPLETE_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_EE_COMPLETE);
}

/* Default interrupt handler for FL_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK void _FL_COMPLETE_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_FL_COMPLETE);
}

/* Default interrupt handler for COLIN_OWNMTX.
 * The handler can be overwritten by application sources. */
WEAK void _COLIN_OWNMTX_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_COLIN_OWNMTX);
}

/* Default interrupt handler for COLIN_LIN.
 * The handler can be overwritten by application sources. */
WEAK void _COLIN_LIN_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_COLIN_LIN);
}

/* Default interrupt handler for OV_VS.
 * The handler can be overwritten by application sources. */
WEAK void _OV_VS_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_OV_VS);
}

/* Default interrupt handler for DIAG.
 * The handler can be overwritten by application sources. */
WEAK void _DIAG_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_DIAG);
}

/* Default interrupt handler for I2C_GLOBAL_RESET.
 * The handler can be overwritten by application sources. */
WEAK void _I2C_GLOBAL_RESET_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_I2C_GLOBAL_RESET);
}

/* Default interrupt handler for PPM_RX.
 * The handler can be overwritten by application sources. */
WEAK void _PPM_RX_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PPM_RX);
}

/* Default interrupt handler for PPM_TX.
 * The handler can be overwritten by application sources. */
WEAK void _PPM_TX_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PPM_TX);
}

/* Default interrupt handler for PPM_ERR.
 * The handler can be overwritten by application sources. */
WEAK void _PPM_ERR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_PPM_ERR);
}

/* Default interrupt handler for IO_IN0.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN0_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN0);
}

/* Default interrupt handler for IO_IN1.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN1_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN1);
}

/* Default interrupt handler for IO_IN2.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN2_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN2);
}

/* Default interrupt handler for IO_IN3.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN3_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN3);
}

#if defined(MLX81332) || defined(MLX81334)
/* Default interrupt handler for IO_IN4.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN4_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN4);
}

/* Default interrupt handler for IO_IN5.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN5_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN5);
}

/* Default interrupt handler for IO_IN6.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN6_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN6);
}

/* Default interrupt handler for IO_IN7.
 * The handler can be overwritten by application sources. */
WEAK void _IO_IN7_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_IO_IN7);
}

/* Default interrupt handler for UART_SB.
 * The handler can be overwritten by application sources. */
WEAK void _UART_SB_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UART_SB);
}

/* Default interrupt handler for UART_RS.
 * The handler can be overwritten by application sources. */
WEAK void _UART_RS_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UART_RS);
}

/* Default interrupt handler for UART_RR.
 * The handler can be overwritten by application sources. */
WEAK void _UART_RR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UART_RR);
}

/* Default interrupt handler for UART_TS.
 * The handler can be overwritten by application sources. */
WEAK void _UART_TS_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UART_TS);
}

/* Default interrupt handler for UART_TR.
 * The handler can be overwritten by application sources. */
WEAK void _UART_TR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UART_TR);
}

/* Default interrupt handler for UART_TE.
 * The handler can be overwritten by application sources. */
WEAK void _UART_TE_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UART_TE);
}

/* Default interrupt handler for UDFR.
 * The handler can be overwritten by application sources. */
WEAK void _UDFR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UDFR);
}

/* Default interrupt handler for UDTF.
 * The handler can be overwritten by application sources. */
WEAK void _UDTF_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_UDTF);
}
#endif /* defined (MLX81332) || defined (MLX81334) */

/* Default interrupt handler for TX_TIMEOUT.
 * The handler can be overwritten by application sources. */
WEAK void _TX_TIMEOUT_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_TX_TIMEOUT);
}

#if defined(MLX81334)
/* Default interrupt handler for I2C_EOW.
 * The handler can be overwritten by application sources. */
WEAK void _I2C_EOW_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_I2C_EOW);
}

/* Default interrupt handler for I2C_EOR.
 * The handler can be overwritten by application sources. */
WEAK void _I2C_EOR_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_I2C_EOR);
}
#endif /* defined (MLX81334) */

/* Default interrupt handler for MLX16_SOFT.
 * The handler can be overwritten by application sources. */
WEAK void _MLX16_SOFT_INT(void)
{
    ErrH_NonInlineVectorFatalInformed(MEM_FLASH_VECTORS_START + MEM_FLASH_VECTOR_OFFSET_MLX16_SOFT);
}

#endif /* HAS_SW_EXPLICIT_FAIL_INFO */
