SPI__DR
SPI__SBASE
SPI__RBASE
SPI__MSGLEN
SPI__DR
SPI__PSCL & 0xF
(SPI__PSCL >> 4)
(28000000>>(SPI__PSCL & 0xF))/((SPI__PSCL >> 4) + 1)
PORT_IO_TRIG_EDGE_CFG__0X0240
PORT_IO_OUT_SOFT__IO_OUT_SOFT
PORT_IO_OUT_EN__0X01E8
PORT_IO_CFG0__0X01EA
PORT_IO_ENABLE__0X023A
STIMER__CURRENT
(STIMER__VALUE+ (STIMER__MODE << 8)) & 0x3FFF
